# Generated by Django 4.2.2 on 2023-06-22 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF must be in the format XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('approved_by_ai', 'Approved by AI'), ('approved_by_human', 'Approved by Human'), ('rejected_by_ai', 'Rejected by AI'), ('rejected_by_human', 'Rejected by Human')], default='processing', max_length=20)),
                ('requested_infos', models.CharField(max_length=1000)),
            ],
        ),
    ]
