# Generated by Django 4.2.2 on 2023-06-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='requested_infos',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
